settings:
  title: 'Status Page'
  url: 'https://status.studyinglover.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: studyinglover home page # unique identifier
    name: studyinglover.com
    description: 'studyinglover home page' # default=empty
    url: 'https://studyinglover.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true

  - id: studyinglover.top home page
    name: studyinglover.top
    description: 'studyinglover home page'
    url: 'https://studyinglover.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: serv00
    name: serv00 
    url: 'https://studyinglover.serv00.net/info'
    method: GET
    expectStatus: 200
